--- !!ExptConfig
dataFilePath: data/example.csv
experimentPeriodInDays: 28
populationSize: 39
dutyCycleLengthInMinutes: 5.0
rssiThreshold: -80
contagiousEventRatePerDay: 288.0
diseaseName: basic_flu
diseaseR0: 3
incubationPeriodInDays_min: 1.0
incubationPeriodInDays_max: 4.0
infectiousPeriodInDays_min: 3.0
infectiousPeriodInDays_max: 5.0
samplingMethod: UPPERBOUND
samplingPeriodInMinutes: [5]
seed: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

